# Generated by Django 3.0 on 2020-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('initial', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
